kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.amq-broker.namespace }} factory-amq-broker
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-broker
  namespace: {{ .Values.amq-broker.namespace }}
spec:
  channel: current
  installPlanApproval: Automatic
  name: amq-broker
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ .Values.amq-broker.startingCSV }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.amq-broker.namespace }}
  namespace: {{ .Values.amq-broker.namespace }}
spec:
  targetNamespaces:
    - {{ .Values.amq-broker.namespace }}
---
apiVersion: broker.amq.io/v2alpha4
kind: ActiveMQArtemis
metadata:
  name: {{ .Values.amq-broker.brokerName }}
  application: {{ .Values.amq-broker.brokerName }}
  namespace: {{ .Values.amq-broker.namespace }}
spec:
  adminPassword: {{ .Values.amq-broker.adminPassword }}
  deploymentPlan:
    size: {{ .Values.amq-broker.size }}
    persistenceEnabled: false
    requireLogin: false
    messageMigration: false
    managementRBACEnabled: true
    journalType: nio
    jolokiaAgentEnabled: false
    image: placeholder
  adminUser: {{ .Values.amq-broker.adminUser }}