kind: Namespace
apiVersion: v1
metadata:
  name: factory-amq-broker
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/amq-broker.factory-amq-broker: ''
  name: amq-broker
  namespace: factory-amq-broker
spec:
  channel: current
  installPlanApproval: Automatic
  name: amq-broker
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: amq-broker-operator.v7.8.1-opr-3
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: factory-amq-broker
  namespace: factory-amq-broker
spec:
  targetNamespaces:
    - factory-amq-broker
---
apiVersion: broker.amq.io/v2alpha4
kind: ActiveMQArtemis
metadata:
  name: factory01-broker
  application: factory01-app
  namespace: factory-amq-broker
spec:
  adminPassword: qiotmanufacturingpassword
  deploymentPlan:
    size: 1
    persistenceEnabled: false
    requireLogin: false
    messageMigration: false
    managementRBACEnabled: true
    journalType: nio
    jolokiaAgentEnabled: false
    image: placeholder
  adminUser: qiotmanufacturing