kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.mongo.namespace }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: mongodb
  namespace: {{ .Values.mongo.namespace }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:openshift:scc:privileged'
  namespace: {{ .Values.mongo.namespace }}
subjects:
  - kind: ServiceAccount
    name: mongodb
    namespace: {{ .Values.mongo.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:privileged'
---
  apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: mongodb-pv
    labels:
      type: local
  spec:
    storageClassName: manual 
    capacity:
      storage: {{ .Values.mongo.storageCapacity }}
    accessModes:
      - ReadWriteOnce 
    persistentVolumeReclaimPolicy: Retain
    hostPath:
      path: {{ .Values.mongo.path }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: {{ .Values.mongo.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongo.storageCapacity }}
  storageClassName: manual
---
kind: Secret
apiVersion: v1
metadata:
  name: mongodb
  namespace: {{ .Values.mongo.namespace }}
stringData:
  MONGODB_ADMIN_PASSWORD: {{ .Values.mongo.MONGODB_ADMIN_PASSWORD }}
  MONGODB_DATABASE: {{ .Values.mongo.MONGODB_DATABASE }}
  MONGODB_PASSWORD: {{ .Values.mongo.MONGODB_PASSWORD }}
  MONGODB_USER: {{ .Values.mongo.MONGODB_USER }}
type: Opaque
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongodb
  namespace: {{ .Values.mongo.namespace }}
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongodb
        deploymentconfig: mongodb
    spec:
      restartPolicy: Always
      serviceAccountName: mongodb
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsUser: 0
      containers:
        - resources:
            limits:
              cpu: 500m
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          name: mongodb
          ports:
            - containerPort: 27017
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: mongodb-1
              mountPath: /var/lib/mongodb/data
          terminationMessagePolicy: File
          envFrom:
            - secretRef:
                name: mongodb
          image: >-
            registry.redhat.io/rhscl/mongodb-36-rhel7@sha256:8dc9932eabd30f2ee4d0b882500c65b48f3c2fbbd85bfd51d0d18410af404a39
      serviceAccount: mongodb
      volumes:
        - name: mongodb-1
          persistentVolumeClaim:
            claimName: mongodb-pvc
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: mongodb
  namespace: {{ .Values.mongo.namespace }}
spec:
  ports:
    - name: 27017-tcp
      protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: mongodb
    deploymentconfig: mongodb
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack