version: '3'
services:

  manufacturing-factory-broker:
    image: vromero/activemq-artemis:latest-alpine
    container_name: "manufacturing-factory-broker"
    restart: "always"
    networks:
      - manufacturing-factory
      - manufacturing-factoryconnect
    ports:
    - "61616:61616"
    - "1883:1883"
    - "5672:5672"
    - "8161:8161"
    environment:
      ARTEMIS_USERNAME: "qiotmanufacturing"
      ARTEMIS_PASSWORD: "qiotmanufacturingpassword"

  manufacturing-factory-sqlstorage:
    image: postgres
    container_name: "manufacturing-factory-sqlstorage"
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "qiotmanufacturing"
      POSTGRES_PASSWORD: "qiotmanufacturingpassword"
      POSTGRES_DB: "qiot_manufacturing"
      
  manufacturing-factory-nosqlstorage:
    image: mongo
    container_name: "manufacturing-factory-nosqlstorage"
    restart: "always"
    networks:
      - manufacturing-factory
    expose:
      - "27017"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: "qiot_manufacturing"
      #MONGO_INITDB_ROOT_USERNAME: "qiotmanufacturing"
      #MONGO_INITDB_ROOT_PASSWORD: "qiotmanufacturingpassword"
      MONGO_INITDB_ROOT_USERNAME: "qiotroot"
      MONGO_INITDB_ROOT_PASSWORD: "qiotrootpassword"
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo-storage:/data/db
      
volumes:
  postgres-storage:
  mongo-storage:
networks:
  manufacturing-datacenterconnect:
    external: true
  manufacturing-factory:
    external: true
  manufacturing-factoryconnect:
    external: true
  default:
    external:
      name: manufacturing-factory


