version: '3'
services:

  activemq:
    image: vromero/activemq-artemis:latest-alpine
    container_name: "manufacturing-factory-broker"
    restart: "always"
    networks:
      - manufacturing-factory
      - manufacturing-factoryconnect
    ports:
    - "61616:61616"
    - "1883:1883"
    - "5672:5672"
    - "8161:8161"
    environment:
      ARTEMIS_USERNAME: "qiotmanufacturing"
      ARTEMIS_PASSWORD: "qiotmanufacturingpassword"

#  activemq:
#    image: quay.io/artemiscloud/activemq-artemis-broker:dev.latest
#    container_name: "manufacturing-factory-broker"
#    restart: "always"
#    networks:
#      - manufacturing-factory
#      - manufacturing-factoryconnect
#    ports:
#    - "61616:61616"
#    - "1883:1883"
#    - "5672:5672"
#    - "8161:8161"
#    environment:
#      AMQ_USER: "qiotmanufacturing"
#      AMQ_PASSWORD: "qiotmanufacturingpassword"

  postgresql:
    image: postgres
    container_name: "manufacturing-factory-sqlstorage"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "qiotmanufacturing"
      POSTGRES_PASSWORD: "qiotmanufacturingpassword"
      POSTGRES_DB: "qiot_manufacturing"
      
  mongo:
    image: mongo
    container_name: "manufacturing-factory-nosqlstorage"
    environment:
      MONGO_INITDB_DATABASE: "qiot_manufacturing"
      #MONGO_INITDB_ROOT_USERNAME: "qiotmanufacturing"
      #MONGO_INITDB_ROOT_PASSWORD: "qiotmanufacturingpassword"
      MONGO_INITDB_ROOT_USERNAME: "qiotroot"
      MONGO_INITDB_ROOT_PASSWORD: "qiotrootpassword"
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo-storage:/data/db
      
volumes:
  postgres-storage:
  mongo-storage:
networks:
  manufacturing-datacenterconnect:
    external: true
  manufacturing-factory:
    external: true
  manufacturing-factoryconnect:
    external: true
  default:
    external:
      name: manufacturing-factory


